using System;
using System.Runtime.Serialization;

namespace OneLogin.Responses
{
    /// <summary>
    /// The response with a set of events.
    /// </summary>
    [DataContract]
    public class GetEventsResponse : PaginationBaseResponse<Event>
    {
    }

    /// <summary>
    /// An onelogin event.
    /// </summary>
    [DataContract]
    public class Event
    {
        /// <summary>
        /// Event’s unique ID in OneLogin. Autogenerated by OneLogin.
        /// </summary>
        [DataMember(Name = "id")]
        public long Id { get; set; }

        /// <summary>
        /// Time and date at which the event was created. This value is autogenerated by OneLogin.
        /// </summary>
        [DataMember(Name = "created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Account that triggered the event.
        /// </summary>
        [DataMember(Name = "account_id")]
        public int AccountId { get; set; }

        /// <summary>
        /// ID of the user that was acted upon to trigger the event.
        /// </summary>
        [DataMember(Name = "user_id")]
        public int? UserId { get; set; }

        /// <summary>
        /// Type of event triggered.
        /// </summary>
        [DataMember(Name = "event_type_id")]
        public int EventTypeId { get; set; }

        /// <summary>
        /// More details about the event.
        /// </summary>
        [DataMember(Name = "notes")]
        public string Notes { get; set; }

        /// <summary>
        /// IP address of the machine used to trigger the event.
        /// </summary>
        [DataMember(Name = "ipaddr")]
        public string IpAddress { get; set; }

        /// <summary>
        /// ID of the user whose action triggered the event.
        /// </summary>
        [DataMember(Name = "actor_user_id")]
        public int? ActorUserId { get; set; }

        /// <summary>
        /// Name of the user who assumed the role of the acting user to trigger the event, if applicable.
        /// </summary>
        [DataMember(Name = "assuming_acting_user_id")]
        public int? assuming_acting_user_id { get; set; }

        /// <summary>
        /// ID of a role involved in the event.
        /// </summary>
        [DataMember(Name = "role_id")]
        public int? role_id { get; set; }

        /// <summary>
        /// ID of the app involved in the event, if applicable.
        /// </summary>
        [DataMember(Name = "app_id")]
        public int? app_id { get; set; }

        /// <summary>
        /// ID of a group involved in the event.
        /// </summary>
        [DataMember(Name = "group_id")]
        public string group_id { get; set; }

        /// <summary>
        /// ID of a device involved in the event.
        /// </summary>
        [DataMember(Name = "otp_device_id")]
        public string otp_device_id { get; set; }

        /// <summary>
        /// ID of the policy involved in the event.
        /// </summary>
        [DataMember(Name = "policy_id")]
        public string policy_id { get; set; }

        /// <summary>
        /// Acting system that triggered the event when the actor is not a user.
        /// </summary>
        [DataMember(Name = "actor_system")]
        public string actor_system { get; set; }

        /// <summary>
        /// More details about the event.
        /// </summary>
        [DataMember(Name = "custom_message")]
        public string custom_message { get; set; }

        /// <summary>
        /// Name of a role involved in the event.
        /// </summary>
        [DataMember(Name = "role_name")]
        public string role_name { get; set; }

        /// <summary>
        /// Name of the app involved in the event, if applicable.
        /// </summary>
        [DataMember(Name = "app_name")]
        public string app_name { get; set; }

        /// <summary>
        /// Name of a group involved in the event.
        /// </summary>
        [DataMember(Name = "group_name")]
        public string group_name { get; set; }

        /// <summary>
        /// First and last name of the user whose action triggered the event.
        /// </summary>
        [DataMember(Name = "actor_user_name")]
        public string actor_user_name { get; set; }

        /// <summary>
        /// Name of the user that was acted upon to trigger the event.
        /// </summary>
        [DataMember(Name = "user_name")]
        public string user_name { get; set; }

        /// <summary>
        /// Name of the policy involved in the event.
        /// </summary>
        [DataMember(Name = "policy_name")]
        public string policy_name { get; set; }

        /// <summary>
        /// Name of a device involved in the event.
        /// </summary>
        [DataMember(Name = "otp_device_name")]
        public string otp_device_name { get; set; }

        /// <summary>
        /// Name of operation involved in the event.
        /// </summary>
        [DataMember(Name = "operation_name")]
        public string operation_name { get; set; }

        /// <summary>
        /// Directory sync run ID.
        /// </summary>
        [DataMember(Name = "directory_sync_run_id")]
        public string directory_sync_run_id { get; set; }

        /// <summary>
        /// Event’s unique ID in OneLogin. Autogenerated by OneLogin.
        /// </summary>
        [DataMember(Name = "directory_id")]
        public string directory_id { get; set; }

        /// <summary>
        /// Event’s unique ID in OneLogin. Autogenerated by OneLogin.
        /// </summary>
        [DataMember(Name = "resolution")]
        public string resolution { get; set; }

        /// <summary>
        /// Client ID used to generate the access token that made the API call that generated the event.
        /// </summary>
        [DataMember(Name = "client_id")]
        public string client_id { get; set; }

        /// <summary>
        /// ID of the resource (user, role, group, and so forth) associated with the event.
        /// </summary>
        [DataMember(Name = "resource_type_id")]
        public string resource_type_id { get; set; }

        /// <summary>
        /// Provisioning error details, if applicable.
        /// </summary>
        [DataMember(Name = "error_description")]
        public string error_description { get; set; }

        /// <summary>
        /// Event’s unique ID in OneLogin. Autogenerated by OneLogin.
        /// </summary>
        [DataMember(Name = "proxy_ip")]
        public string proxy_ip { get; set; }
    }
}
